# Specify the base image
FROM node:lts-alpine

# Specify a working directory for your application
WORKDIR /app

RUN apk update && apk add nano

# Copy our package files. Copy the other files later to avoid unnecessary rebuilds
COPY package*.json ./
COPY ./yarn.lock ./

# Install some dependencies
RUN yarn

# Copy rest of the files
COPY ./ ./

# Default command
CMD ["yarn", "start"]